title:       Emil Schmitz
author:      Emil Schmitz
description: "Research and Engineering"
baseurl:     ""
url:         "https://emilschmitz.github.io"
github_username: emilschmitz
linkedin_username: emil-schmitz-1ba787a4

markdown:     kramdown
permalink:    pretty
kramdown:
  math_engine: null
  input: GFM
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
